apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "traefik-{{name}}" # name is the cluster name
    spec:
      project: default
      source:
        repoURL: https://traefik.github.io/charts
        targetRevision: 39.0.0
        chart: traefik
        helm:
          values: |
            ingressRoute:
              dashboard:
                enabled: true
                matchRule: Host(`traefik.{{name}}.example.com`)
                entryPoints:
                  - web
            providers:
              kubernetesGateway:
                enabled: true
            gateway:
              listeners:
                web:
                  namespacePolicy:
                    from: All
      destination:
        server: "{{server}}"
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
