apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://helm.digitalstudium.com"
      chart: argocd-appsets
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/values/infra/vmkube-1/argocd-appsets.yaml
    - repoURL: https://github.com/digitalstudium/devops-homelab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
