apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cluster-pool
spec:
  addresses:
    - "192.168.193.1-192.168.193.254"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
spec:
  ipAddressPools:
    - cluster-pool
