apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-infra-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://helm.digitalstudium.com"
      chart: argocd-apps
      targetRevision: 0.4.0
      helm:
        valueFiles:
          - $values/values/vmkube-1/argocd-apps.yaml
    - repoURL: https://gitlab.homelab.internal/devops/argocd-apps.git
      targetRevision: HEAD
      ref: values
  destination:
    name: vmkube-1
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
