kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: "postgres-cluster"
  labels:
    team: acid
spec:
  teamId: "acid"
  postgresql:
    version: "17"
  numberOfInstances: 3
  enableMasterLoadBalancer: true
  volume:
    size: "1Gi"
  users:
    grafana: []
  databases:
    grafana: grafana
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
