## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
itemTemplates:
  # for non-oci helm charts
  - items:
      - name: cert-manager
        helmRepo: https://charts.jetstack.io
        helmVersion: v1.19.3
      - name: postgres-operator
        helmRepo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
        helmVersion: 1.15.1
      - name: metallb
        helmRepo: https://metallb.github.io/metallb
        helmVersion: 0.15.3
        privileged: true
      - name: local-path-provisioner
        helmRepo: https://charts.containeroo.ch
        helmVersion: v0.0.35
    template:
      apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        name: "{{ .name }}"
      spec:
        goTemplate: true
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
        template:
          metadata:
            name: "{{`{{ .name }}`}}-{{ .name }}"
          spec:
            project: default
            sources:
              - repoURL: "{{ .helmRepo }}"
                targetRevision: "{{ .helmVersion }}"
                chart: "{{ .name }}"
                helm:
                  valueFiles:
                    - $values/values/infra/{{ .name }}.yaml
                  ignoreMissingValueFiles: true
              - repoURL: https://github.com/digitalstudium/devops-homelab.git
                targetRevision: HEAD
                ref: values
            destination:
              server: "{{`{{server}}`}}"
              namespace: "{{ .name }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - ApplyOutOfSyncOnly=true
            templatePatch: |
              {{- if .privileged }}
              spec:
                syncPolicy:
                  managedNamespaceMetadata:
                    labels:
                      pod-security.kubernetes.io/enforce: privileged
              {{- end }}
  # for oci helm charts
  - items:
      - name: spegel
        helmRepo: oci://ghcr.io/spegel-org/helm-charts/spegel
        helmVersion: 0.6.0
    template:
      apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        name: "{{ .name }}"
      spec:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
        template:
          metadata:
            name: "{{`{{name}}`}}-{{ .name }}"
          spec:
            project: default
            sources:
              - repoURL: "{{ .helmRepo }}"
                targetRevision: "{{ .helmVersion }}"
                path: .
                helm:
                  valueFiles:
                    - $values/values/infra/{{ .name }}.yaml
                  ignoreMissingValueFiles: true
              - repoURL: https://github.com/digitalstudium/devops-homelab.git
                targetRevision: HEAD
                ref: values
            destination:
              server: "{{`{{server}}`}}"
              namespace: "{{ .name }}"
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
                - ServerSideApply=true
                - ApplyOutOfSyncOnly=true
