valuesRepo: https://github.com/digitalstudium/devops-homelab.git

charts:
  - name: spegel
    helmRepo: oci://ghcr.io/spegel-org/helm-charts/spegel
    helmVersion: 0.6.0
    privileged: true
    oci: true
  - name: cert-manager
    helmRepo: https://charts.jetstack.io
    helmVersion: v1.19.3
  - name: postgres-operator
    helmRepo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    helmVersion: 1.15.1
  - name: traefik
    helmRepo: https://traefik.github.io/charts
    helmVersion: 39.0.0
  - name: victoria-metrics-k8s-stack
    helmRepo: https://victoriametrics.github.io/helm-charts
    helmVersion: 0.70.0
    privileged: true
  - name: metallb
    helmRepo: https://metallb.github.io/metallb
    helmVersion: 0.15.3
    privileged: true
  - name: local-path-provisioner
    helmRepo: https://charts.containeroo.ch
    helmVersion: v0.0.35
    privileged: true
