apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-store
spec:
  provider:
    vault:
      server: "https://openbao.vmkube-1.homelab.internal"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "vmkube-1"
          role: "eso-role"
          serviceAccountRef:
            name: "vmkube-1-external-secrets"
            namespace: "external-secrets"            
      caProvider:
        type: "Secret"
        namespace: "external-secrets"
        name: "root-secret-cacert"
        key: "ca.crt"
